theme: jekyll-theme-minimal
title: Henry Van Orden's homepage
description: Bookmark this to keep an eye on my project updates!
links:
  - title: Resume
    url: resume.pdf
  - title: Email Me
    url: mailto:henryvanorden@gmail.com
  - title: GitHub Profile
    url: https://github.com/henryvanorden-crypto
